const map=L.map('map',{zoomControl:true}).setView([36.5,138.0],5);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
let incident=null,incidentMarker=null,routeLayer=null;let roadTimes={},roadDistances={};const markers=new Map();

function setIncident(lat,lng,label="発災地点"){incident={lat,lng};if(incidentMarker)map.removeLayer(incidentMarker);incidentMarker=L.marker([lat,lng],{draggable:true}).addTo(map).bindPopup(label).openPopup();incidentMarker.on("dragend",e=>{const p=e.target.getLatLng();setIncident(p.lat,p.lng)});incidentText.textContent=`緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;roadTimes={};roadDistances={};render()}
map.on("click",e=>setIncident(e.latlng.lat,e.latlng.lng));map.on("contextmenu",e=>setIncident(e.latlng.lat,e.latlng.lng));

async function searchAddress(){const q=addressInput.value.trim();if(!q)return alert("住所・施設名などを入力してください。");addressBtn.disabled=true;status.textContent="地点を検索中…";searchCandidates.style.display="none";try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=8&countrycodes=jp&addressdetails=1&namedetails=1&q=${encodeURIComponent(q)}`,{headers:{"Accept-Language":"ja"}});const j=await r.json();if(!j.length){status.textContent="該当地点が見つかりません。";return}searchCandidates.innerHTML=j.map((x,i)=>`<div class="candidate" data-i="${i}"><b>${x.namedetails?.name||x.name||(x.display_name||"").split(",")[0]}</b><div class="small">${x.display_name||""}</div></div>`).join("");searchCandidates.style.display="block";searchCandidates.querySelectorAll(".candidate").forEach(el=>el.onclick=()=>{const x=j[Number(el.dataset.i)],lat=Number(x.lat),lng=Number(x.lon),label=x.namedetails?.name||x.name||q;setIncident(lat,lng,label);map.setView([lat,lng],13);incidentText.innerHTML=`<b>${label}</b><br>${x.display_name||""}<br>緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;searchCandidates.style.display="none";status.textContent="発災地点を設定しました。";});status.textContent=`${j.length}件の候補が見つかりました。`}catch(e){status.textContent="地点検索に失敗しました。"}finally{addressBtn.disabled=false}}
addressBtn.onclick=searchAddress;addressInput.addEventListener("keydown",e=>{if(e.key==="Enter")searchAddress()});
geoBtn.onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{setIncident(p.coords.latitude,p.coords.longitude,"現在地");map.setView([p.coords.latitude,p.coords.longitude],13)},()=>alert("現在地を取得できませんでした。"));
clearBtn.onclick=()=>{incident=null;if(incidentMarker)map.removeLayer(incidentMarker);incidentMarker=null;incidentText.textContent="未設定";roadTimes={};roadDistances={};render()};

function hav(a,b){const R=6371,tr=x=>x*Math.PI/180,dLat=tr(b.lat-a.lat),dLon=tr(b.lng-a.lng),z=Math.sin(dLat/2)**2+Math.cos(tr(a.lat))*Math.cos(tr(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
function airMin(km){return km/(Number(airSpeed.value)||220)*60+(Number(airOverhead.value)||0)}

async function findHospitals(){if(!incident)return alert("先に発災地点を指定してください。");findHospBtn.disabled=true;status.textContent="周辺病院を検索中…";hospitals.splice(0,hospitals.length);roadTimes={};roadDistances={};markers.forEach(m=>map.removeLayer(m));markers.clear();const radius=Number(radiusKm.value)*1000;const q=`[out:json][timeout:25];(nwr["amenity"="hospital"](around:${radius},${incident.lat},${incident.lng}););out center tags;`;try{const r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"data="+encodeURIComponent(q)});if(!r.ok)throw 0;const j=await r.json();const seen=new Set();for(const e of j.elements){const lat=e.lat??e.center?.lat,lng=e.lon??e.center?.lon,name=e.tags?.["name:ja"]||e.tags?.name;if(!lat||!lng||!name)continue;const key=name+"|"+lat.toFixed(4)+"|"+lng.toFixed(4);if(seen.has(key))continue;seen.add(key);hospitals.push({name,lat,lng,address:[e.tags?.["addr:province"],e.tags?.["addr:city"],e.tags?.["addr:full"],e.tags?.["addr:street"]].filter(Boolean).join(" "),dist:hav(incident,{lat,lng})})}hospitals.sort((a,b)=>a.dist-b.dist);hospitals.splice(Number(maxHosp.value));drawHospitals();render();status.textContent=`${hospitals.length}施設を表示しました。`;if(hospitals.length===0)status.textContent="周辺病院が見つかりませんでした。検索半径を広げてください。"}catch(e){status.textContent="周辺病院検索に失敗しました。公開検索サービスが混雑している可能性があります。"}finally{findHospBtn.disabled=false}}
findHospBtn.onclick=findHospitals;

function drawHospitals(){markers.forEach(m=>map.removeLayer(m));markers.clear();hospitals.forEach((h,i)=>{const m=L.circleMarker([h.lat,h.lng],{radius:7,color:"#fff",weight:1,fillColor:"#3b82f6",fillOpacity:.95}).addTo(map).bindPopup(`<b>${h.name}</b><br>${h.address||""}<br>直線 ${h.dist.toFixed(1)} km`);markers.set(i,m)})}

function render(){let arr=hospitals.map((h,i)=>({h,i,dist:incident?hav(incident,h):h.dist,road:roadTimes[i],air:incident?airMin(hav(incident,h)):null}));const mode=sortMode.value;arr.sort((a,b)=>mode==="road"?(a.road??1e9)-(b.road??1e9):mode==="air"?(a.air??1e9)-(b.air??1e9):mode==="name"?a.h.name.localeCompare(b.h.name,"ja"):(a.dist??1e9)-(b.dist??1e9));hospitalCount.textContent=arr.length;results.innerHTML=arr.map(x=>`<div class="result" data-i="${x.i}"><div class="name">${x.h.name}</div><div class="meta">${x.h.address||"所在地情報なし"} ・ 直線 ${x.dist.toFixed(1)} km</div><div class="times"><span class="pill road">陸路 ${x.road!=null?Math.round(x.road)+"分 / "+roadDistances[x.i].toFixed(1)+"km":"未計算"}</span><span class="pill air">空路 約${Math.round(x.air)}分</span></div></div>`).join("");document.querySelectorAll(".result").forEach(el=>el.onclick=()=>showRoute(Number(el.dataset.i)))}
sortMode.onchange=render;airSpeed.oninput=render;airOverhead.oninput=render;

async function routeOne(i,geometry=false){const h=hospitals[i];const url=`https://router.project-osrm.org/route/v1/driving/${incident.lng},${incident.lat};${h.lng},${h.lat}?overview=${geometry?"full":"false"}&geometries=geojson`;const r=await fetch(url),j=await r.json(),rt=j.routes?.[0];if(!rt)throw 0;return rt}
async function calcRoad(){if(!incident)return alert("先に発災地点を指定してください。");if(!hospitals.length)return alert("先に周辺病院を検索してください。");calcBtn.disabled=true;roadTimes={};roadDistances={};let done=0;for(let k=0;k<hospitals.length;k+=4){await Promise.all(hospitals.slice(k,k+4).map(async(_,j)=>{const i=k+j;try{const rt=await routeOne(i,false);roadTimes[i]=rt.duration/60;roadDistances[i]=rt.distance/1000;done++}catch(e){}}));status.textContent=`陸路計算中… ${Math.min(k+4,hospitals.length)}/${hospitals.length}`;render()}status.textContent=`${done}施設の陸路を計算しました。`;calcBtn.disabled=false}
calcBtn.onclick=calcRoad;
async function showRoute(i){if(!incident)return;status.textContent=`${hospitals[i].name}へのルートを取得中…`;try{const rt=await routeOne(i,true);if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.geoJSON(rt.geometry,{style:{weight:5,opacity:.8}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[30,30]});roadTimes[i]=rt.duration/60;roadDistances[i]=rt.distance/1000;render();status.textContent=`${hospitals[i].name}: 約${Math.round(rt.duration/60)}分 / ${(rt.distance/1000).toFixed(1)} km`}catch(e){status.textContent="ルート取得に失敗しました。"}}
render();