const map=L.map('map',{zoomControl:true}).setView([37.40,140.30],9);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
let incident=null,incidentMarker=null,routeLayer=null,roadTimes={},roadDistances={};
const hospitalLayers=new Map();
function iconColor(h){return h.critical?'#ef4444':h.disaster?'#f59e0b':'#3b82f6'}
function visible(h){return (h.critical&&fCritical.checked)||(h.disaster&&fDisaster.checked)||(h.secondary&&fSecondary.checked)}
function catText(h){let x=[];if(h.critical)x.push("救命救急");if(h.disaster)x.push("災害拠点");if(h.secondary)x.push("二次救急医療機関");return x.join(" / ")}
function addHospitalMarker(h,i){if(h.lat==null||h.lng==null||!visible(h))return false;if(hospitalLayers.has(i))return true;const m=L.circleMarker([h.lat,h.lng],{radius:h.critical?8:6,color:"#fff",weight:1,fillColor:iconColor(h),fillOpacity:.95}).addTo(map).bindPopup(`<b>${h.name}</b><br>${catText(h)}<br>${h.area}<br>${h.address||""}`);hospitalLayers.set(i,m);return true}
async function geocodeHospital(h){if(h.lat!=null&&h.lng!=null)return true;try{const r=await fetch(`https://msearch.gsi.go.jp/address-search/AddressSearch?q=${encodeURIComponent(h.address||("福島県 "+h.name))}`);if(!r.ok)throw 0;const j=await r.json();if(!j?.length)throw 0;h.lng=Number(j[0].geometry.coordinates[0]);h.lat=Number(j[0].geometry.coordinates[1]);return Number.isFinite(h.lat)&&Number.isFinite(h.lng)}catch(e){try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=jp&q=${encodeURIComponent(h.name+" "+(h.address||"福島県"))}`,{headers:{"Accept-Language":"ja"}});const j=await r.json();if(!j?.length)return false;h.lat=Number(j[0].lat);h.lng=Number(j[0].lon);return true}catch(e2){return false}}}
async function drawHospitals(){hospitalLayers.forEach(x=>map.removeLayer(x));hospitalLayers.clear();hospitals.forEach((h,i)=>addHospitalMarker(h,i));status.textContent=`二次救急医療機関をプロット中… ${hospitalLayers.size}/69`;const pending=hospitals.map((h,i)=>({h,i})).filter(x=>x.h.lat==null||x.h.lng==null);for(let k=0;k<pending.length;k+=5){await Promise.all(pending.slice(k,k+5).map(async x=>{if(await geocodeHospital(x.h))addHospitalMarker(x.h,x.i)}));status.textContent=`二次救急医療機関をプロット中… ${hospitalLayers.size}/69`}status.textContent=hospitalLayers.size===69?"二次救急医療機関 69施設を地図上にプロットしました。":`${hospitalLayers.size}/69施設をプロットしました。`;if(hospitalLayers.size>1&&!incident){const pts=[];hospitalLayers.forEach(m=>pts.push(m.getLatLng()));map.fitBounds(L.latLngBounds(pts),{padding:[20,20]})}renderResults()}
drawHospitals();
function setIncident(lat,lng){incident={lat,lng};if(incidentMarker)map.removeLayer(incidentMarker);incidentMarker=L.marker([lat,lng],{draggable:true}).addTo(map).bindPopup("発災地点").openPopup();incidentMarker.on('dragend',e=>{const p=e.target.getLatLng();setIncident(p.lat,p.lng)});incidentText.textContent=`緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;renderResults()}
map.on('click',e=>setIncident(e.latlng.lat,e.latlng.lng));map.on('contextmenu',e=>setIncident(e.latlng.lat,e.latlng.lng));
async function searchAddress(){const q=addressInput.value.trim(),box=searchCandidates;if(!q){alert("住所、病院名、店舗名、施設名などを入力してください。");return}addressBtn.disabled=true;status.textContent="地点を検索中…";box.style.display="none";try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&namedetails=1&limit=10&countrycodes=jp&q=${encodeURIComponent(q)}`,{headers:{"Accept-Language":"ja"}});const j=await r.json();if(!j.length){status.textContent="該当地点が見つかりません。";return}const ranked=[...j].sort((a,b)=>((a.display_name||"").includes("福島県")?0:1)-((b.display_name||"").includes("福島県")?0:1)).slice(0,8);box.innerHTML=ranked.map((x,i)=>`<div class="candidate" data-candidate="${i}"><div class="ctitle">${x.namedetails?.name||x.name||(x.display_name||"").split(",")[0]}</div><div class="cmeta">${x.display_name||""}</div></div>`).join("");box.style.display="block";status.textContent=`${ranked.length}件の候補が見つかりました。`;box.querySelectorAll(".candidate").forEach(el=>el.onclick=()=>{const hit=ranked[Number(el.dataset.candidate)],lat=Number(hit.lat),lng=Number(hit.lon),title=hit.namedetails?.name||hit.name||(hit.display_name||"").split(",")[0]||q;setIncident(lat,lng);map.setView([lat,lng],14);incidentText.innerHTML=`<b>${title}</b><br>${hit.display_name||""}<br>緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;addressInput.value=title;box.style.display="none";status.textContent="発災地点を設定しました。"})}catch(e){status.textContent="地点検索に失敗しました。"}finally{addressBtn.disabled=false}}
addressBtn.onclick=searchAddress;addressInput.addEventListener("keydown",e=>{if(e.key==="Enter")searchAddress()});
geoBtn.onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{setIncident(p.coords.latitude,p.coords.longitude);map.setView([p.coords.latitude,p.coords.longitude],12)},()=>alert("現在地を取得できませんでした。"));
clearBtn.onclick=()=>{incident=null;if(incidentMarker)map.removeLayer(incidentMarker);incidentMarker=null;incidentText.textContent="未設定";roadTimes={};roadDistances={};if(routeLayer)map.removeLayer(routeLayer);renderResults()};
[fCritical,fDisaster,fSecondary].forEach(x=>x.onchange=()=>drawHospitals());[airSpeed,airOverhead].forEach(x=>x.oninput=renderResults);sortMode.onchange=renderResults;routeDirection.onchange=()=>{roadTimes={};roadDistances={};renderResults()};
function hav(a,b){if(!a||b.lat==null||b.lng==null)return null;const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),z=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
function airMinutes(km){if(km==null)return null;return km/(Number(airSpeed.value)||220)*60+(Number(airOverhead.value)||0)}
function renderResults(){let arr=hospitals.map((h,i)=>({h,i,dist:incident?hav(incident,h):null,road:roadTimes[i],air:incident?airMinutes(hav(incident,h)):null})).filter(x=>visible(x.h));if(incident){const mode=sortMode.value;arr.sort((a,b)=>mode==="road"?(a.road??1e9)-(b.road??1e9):mode==="air"?(a.air??1e9)-(b.air??1e9):(a.dist??1e9)-(b.dist??1e9))}else{const o={"県北":1,"県中":2,"県南":3,"会津":4,"南会津":5,"相双":6,"いわき":7};arr.sort((a,b)=>(o[a.h.area]||99)-(o[b.h.area]||99)||a.h.name.localeCompare(b.h.name,"ja"))}hospitalCount.textContent=arr.length;results.innerHTML=arr.map(x=>`<div class="hospital" data-i="${x.i}"><div class="name">${x.h.name}</div><div class="meta">${catText(x.h)} ・ ${x.h.area}<br>${x.h.address||""}${x.dist!=null?" ・ 直線 "+x.dist.toFixed(1)+" km":""}</div><div class="times"><span class="pill road">陸路 ${x.road!=null?Math.round(x.road)+"分"+(roadDistances[x.i]!=null?" / "+roadDistances[x.i].toFixed(1)+"km":""):"未計算"}</span><span class="pill air">空路 ${x.air!=null?"約"+Math.round(x.air)+"分":"未計算"}</span></div></div>`).join("");document.querySelectorAll(".hospital").forEach(el=>el.onclick=async()=>{const i=Number(el.dataset.i),h=hospitals[i];if(incident)return showRoute(i);if(h.lat==null)await geocodeHospital(h);if(h.lat!=null){map.setView([h.lat,h.lng],13);addHospitalMarker(h,i);hospitalLayers.get(i)?.openPopup()}})}
async function fetchRouteTime(x){const h=x.h,rev=routeDirection.value==="hospitalToIncident",c1=rev?`${h.lng},${h.lat}`:`${incident.lng},${incident.lat}`,c2=rev?`${incident.lng},${incident.lat}`:`${h.lng},${h.lat}`;const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${c1};${c2}?overview=false&steps=false`),j=await r.json(),route=j.routes?.[0];if(!route)throw 0;return{minutes:route.duration/60,km:route.distance/1000}}
async function calcRoad(){if(!incident){alert("先に発災地点を指定してください。");return}roadTimes={};roadDistances={};let raw=hospitals.map((h,i)=>({h,i})).filter(x=>visible(x.h));status.textContent="病院位置を確認中…";for(let k=0;k<raw.length;k+=5)await Promise.all(raw.slice(k,k+5).map(async x=>{if(x.h.lat==null&&await geocodeHospital(x.h))addHospitalMarker(x.h,x.i)}));let targets=raw.filter(x=>x.h.lat!=null).map(x=>({...x,dist:hav(incident,x.h)})).sort((a,b)=>a.dist-b.dist);if(roadLimit.value!=="all")targets=targets.slice(0,Number(roadLimit.value));let done=0,failed=0;for(let k=0;k<targets.length;k+=4){await Promise.all(targets.slice(k,k+4).map(async x=>{try{const rr=await fetchRouteTime(x);roadTimes[x.i]=rr.minutes;roadDistances[x.i]=rr.km;done++}catch(e){failed++}}));status.textContent=`陸路計算中… ${Math.min(k+4,targets.length)}/${targets.length}`;renderResults()}status.textContent=failed?`${done}施設を計算（${failed}施設失敗）`:`${done}施設の陸路距離・所要時間を計算しました。`;renderResults()}
calcBtn.onclick=calcRoad;
async function showRoute(i){const h=hospitals[i];if(h.lat==null&&!await geocodeHospital(h)){status.textContent="病院位置を取得できませんでした。";return}if(routeLayer)map.removeLayer(routeLayer);const rev=routeDirection.value==="hospitalToIncident",from=rev?`${h.lng},${h.lat}`:`${incident.lng},${incident.lat}`,to=rev?`${incident.lng},${incident.lat}`:`${h.lng},${h.lat}`;try{const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${from};${to}?overview=full&geometries=geojson`),j=await r.json(),route=j.routes?.[0];if(!route)throw 0;routeLayer=L.geoJSON(route.geometry,{style:{weight:5,opacity:.75}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[30,30]});roadTimes[i]=route.duration/60;roadDistances[i]=route.distance/1000;renderResults();status.textContent=`${h.name}: 陸路 約${Math.round(roadTimes[i])}分 / ${roadDistances[i].toFixed(1)} km`}catch(e){status.textContent="ルート取得に失敗しました。"}}
renderResults();